version: '3.3'

services:
  traefik:
    image: traefik
    volumes:
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./traefik/conf.d/:/etc/traefik/conf.d/
    ports:
    - target: 80
      protocol: tcp
      published: 80
    - target: 443
      protocol: tcp
      published: 443
    - target: 8080
      protocol: tcp
      published: 8080
