all:
  vars:
    remote_user: root
    ansible_ssh_user: root
    ansible_ssh_common_args: "-F ./ssh-config"
  children:
    spos:
      children:
        my-server:
          hosts:
            spos-01.kiv.zcu.cz:
